"""Harbor agent whose task prompt is generated by a Cell-zero/2 capsule."""

from __future__ import annotations

import subprocess
from pathlib import Path
from typing import Any, override

from harbor.agents.installed.codex import Codex
from harbor.environments.base import BaseEnvironment
from harbor.models.agent.context import AgentContext


DEFAULT_TASK_CONTEXT = (
    "Work directly in the task environment. Inspect the relevant files, implement "
    "the requested result, and run the available verifier or focused checks."
)


class CellZeroCodex(Codex):
    """Codex executor with hereditary prompt construction supplied by Cell Zero."""

    def __init__(
        self,
        *args: Any,
        task_context: str = DEFAULT_TASK_CONTEXT,
        cell_zero_root: str | None = None,
        **kwargs: Any,
    ) -> None:
        super().__init__(*args, **kwargs)
        self._task_context = task_context
        self._cell_zero_root = Path(cell_zero_root or Path(__file__).resolve().parents[1])
        self._renderer = (
            self._cell_zero_root / "scripts" / "render-homoiconic-task.lisp"
        )

    @staticmethod
    @override
    def name() -> str:
        return "cell-zero-codex"

    @override
    def version(self) -> str:
        return "0.2.0"

    def _render_cell_zero_prompt(self, instruction: str) -> tuple[str, dict[str, str]]:
        self.logs_dir.mkdir(parents=True, exist_ok=True)
        context_path = self.logs_dir / "cell-zero-context.txt"
        instruction_path = self.logs_dir / "cell-zero-instruction.txt"
        prompt_path = self.logs_dir / "cell-zero-prompt.txt"
        metadata_path = self.logs_dir / "cell-zero-capsule.txt"
        context_path.write_text(self._task_context)
        instruction_path.write_text(instruction)

        result = subprocess.run(
            [
                "sbcl",
                "--noinform",
                "--disable-debugger",
                "--script",
                str(self._renderer),
                str(context_path),
                str(instruction_path),
                str(prompt_path),
                str(metadata_path),
            ],
            cwd=self._cell_zero_root,
            capture_output=True,
            text=True,
            timeout=120,
            check=False,
        )
        if result.returncode != 0:
            raise RuntimeError(
                "Cell Zero prompt rendering failed: "
                + (result.stderr or result.stdout or "unknown error")[-4000:]
            )

        metadata: dict[str, str] = {}
        for line in metadata_path.read_text().splitlines():
            key, separator, value = line.partition("=")
            if separator:
                metadata[key] = value
        return prompt_path.read_text(), metadata

    @override
    async def run(
        self,
        instruction: str,
        environment: BaseEnvironment,
        context: AgentContext,
    ) -> None:
        prompt, capsule_metadata = self._render_cell_zero_prompt(instruction)
        try:
            await super().run(prompt, environment, context)
        finally:
            metadata = dict(context.metadata or {})
            metadata["cell_zero"] = {
                **capsule_metadata,
                "adapter": self.name(),
                "adapter_version": self.version(),
            }
            context.metadata = metadata
