// millhaven-gen: Generate a Millhaven city simulation .cell program.
// Usage: millhaven-gen -citizens N -analysts M > millhaven-N.cell
package main

import (
	"flag"
	"fmt"
	"math/rand"
	"os"
	"strings"
)

var firstNames = []string{
	"Rosa", "Tom", "Maya", "Gerald", "Priya", "Elena", "Marcus", "Fatima",
	"James", "Yuki", "Carlos", "Sarah", "Kwame", "Ingrid", "Wei", "Amara",
	"Diego", "Olivia", "Raj", "Linnea", "Omar", "Hannah", "Kenji", "Ava",
	"Dmitri", "Chiara", "Lucas", "Zara", "Esteban", "Isla", "Kofi", "Maren",
	"Aiden", "Leila", "Felix", "Nora", "Dante", "Elsa", "Ravi", "Cleo",
	"Soren", "Adina", "Hugo", "Thea", "Idris", "Vera", "Mateo", "Astrid",
	"Tobias", "Lena", "Nico", "Freya", "Alonso", "Clara", "Kai", "Petra",
	"Jasper", "Mira", "Oscar", "Nell", "Anton", "Soleil", "Emil", "Iris",
	"Leo", "Esme", "Ivan", "June", "Atlas", "Wren", "Cyrus", "Fern",
	"Ezra", "Ruby", "Knox", "Opal", "Cole", "Ivy", "Finn", "Sky",
	"Abel", "Lark", "Dean", "Vale", "Paul", "Gale", "Reed", "Hope",
	"Gray", "Rain", "Hart", "Sage", "Clay", "Dawn", "Glen", "Joy",
	"Wade", "Moon", "Bram", "Star",
}

var lastNames = []string{
	"Delgado", "Harwick", "Chen", "Oates", "Sharma", "Vasquez", "Torres",
	"Nguyen", "Petrov", "Sato", "Okafor", "Berg", "Liu", "Diallo", "Kim",
	"Johansson", "Alvarez", "Reeves", "Singh", "Park", "Müller", "Costa",
	"Fernandez", "Walsh", "Tanaka", "Bakker", "Morales", "Jensen", "Nakamura",
	"Roy", "Fischer", "Santos", "Eriksson", "Patel", "Kowalski", "Abbas",
	"Larsen", "Dubois", "Kato", "Mensah", "Andersson", "Ruiz", "Bergman",
	"Huang", "Ibrahim", "Holm", "Gomez", "Strand", "Cheng", "Adebayo",
}

var occupations = []string{
	"head librarian", "commercial fisherman", "high school teacher",
	"retired mayor", "restaurant owner", "harbor master", "baker",
	"mechanic at the only garage", "mail carrier", "nurse at the clinic",
	"bartender at The Rusty Anchor", "boat builder", "watercolor painter",
	"town clerk", "owner of the general store", "lighthouse keeper",
	"retired naval officer", "yoga instructor", "freelance journalist",
	"boat charter operator", "antique dealer", "kindergarten teacher",
	"part-time fisherman and carpenter", "town historian",
	"community garden coordinator", "owner of the bookshop",
	"veterinarian", "volunteer firefighter", "folk musician",
	"retired schoolteacher", "marine biologist at the field station",
	"owner of the bed and breakfast", "crab pot maker",
	"surf instructor in summer, handyman in winter",
	"ferry operator", "owner of the ice cream shop",
	"stone mason", "beekeeper", "weaver", "cheese maker",
	"owner of the hardware store", "piano tuner",
	"net mender", "seaweed harvester", "whale watch guide",
	"pottery teacher", "bicycle repair specialist",
	"owner of the fish and chips stand", "taxi driver",
	"estate agent covering three towns",
}

var ages = []int{
	17, 19, 22, 25, 27, 29, 31, 33, 35, 37, 38, 40, 42, 44, 46, 48,
	50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80,
}

func main() {
	citizens := flag.Int("citizens", 5, "Number of citizens")
	analysts := flag.Int("analysts", 1, "Number of analysts")
	seed := flag.Int64("seed", 42, "Random seed for reproducibility")
	flag.Parse()

	rng := rand.New(rand.NewSource(*seed))

	// Shuffle names
	rng.Shuffle(len(firstNames), func(i, j int) {
		firstNames[i], firstNames[j] = firstNames[j], firstNames[i]
	})
	rng.Shuffle(len(lastNames), func(i, j int) {
		lastNames[i], lastNames[j] = lastNames[j], lastNames[i]
	})
	rng.Shuffle(len(occupations), func(i, j int) {
		occupations[i], occupations[j] = occupations[j], occupations[i]
	})

	if *citizens > len(firstNames) {
		fmt.Fprintf(os.Stderr, "max %d citizens (name pool)\n", len(firstNames))
		os.Exit(1)
	}

	fmt.Printf("-- millhaven-%d.cell: %d citizens + %d analysts in Millhaven\n", *citizens, *citizens, *analysts)
	fmt.Printf("-- Generated by millhaven-gen with seed %d\n\n", *seed)

	// City cell
	fmt.Println(`⊢ city`)
	fmt.Println(`  yield description ≡ "Millhaven is a small coastal town of about 5,000 people. It has a harbor district with fishing boats and seafood restaurants, a main street with shops and a library, a residential hill with Victorian houses, a community park with a bandstand, and an old lighthouse on the point. The weather today is overcast with occasional drizzle. It is a Tuesday in early March."`)
	fmt.Printf("  yield population ≡ %d\n", *citizens)
	fmt.Println(`  yield day ≡ "Tuesday, March 4"`)
	fmt.Println()

	// Generate citizens
	type citizen struct {
		cellName   string
		firstName  string
		lastName   string
		age        int
		occupation string
	}

	allCitizens := make([]citizen, *citizens)
	for i := 0; i < *citizens; i++ {
		first := firstNames[i]
		last := lastNames[i%len(lastNames)]
		age := ages[rng.Intn(len(ages))]
		occ := occupations[i%len(occupations)]

		slug := strings.ToLower(first)
		c := citizen{
			cellName:   fmt.Sprintf("citizen-%s", slug),
			firstName:  first,
			lastName:   last,
			age:        age,
			occupation: occ,
		}
		allCitizens[i] = c

		fmt.Printf("⊢ %s\n", c.cellName)
		fmt.Println("  given city→description")
		fmt.Println("  given city→day")
		fmt.Printf("  yield name ≡ \"%s %s\"\n", c.firstName, c.lastName)
		fmt.Printf("  yield age ≡ %d\n", c.age)
		fmt.Printf("  yield occupation ≡ \"%s\"\n", c.occupation)
		fmt.Println("  yield morning")
		fmt.Println("  yield afternoon")
		fmt.Println("  yield evening")
		fmt.Println("  yield thoughts")
		fmt.Printf("  ∴ You are «name», age «age», %s in Millhaven.\n", articlePrefix(c.occupation))
		fmt.Println("    You live in Millhaven: «description»")
		fmt.Println("    Today is «day».")
		fmt.Println()
		fmt.Println("    Live your day. Describe what you do in the morning, afternoon, and evening.")
		fmt.Println("    Also share your private thoughts — what's on your mind today?")
		fmt.Println()
		fmt.Println("    Be specific about places in Millhaven you visit, people you interact with,")
		fmt.Println("    and things you notice. Stay in character. Be concise but vivid.")
		fmt.Println("  ⊨ morning is a string")
		fmt.Println("  ⊨ afternoon is a string")
		fmt.Println("  ⊨ evening is a string")
		fmt.Println("  ⊨ thoughts is a string")
		fmt.Println()
	}

	// Generate analysts
	analystNames := []string{
		"Dr. Elena Vasquez, computational social scientist",
		"Dr. Marcus Okonkwo, urban anthropologist",
		"Dr. Yuki Tanaka, behavioral economist",
		"Dr. Ingrid Holm, community psychologist",
		"Dr. Kwame Asante, network theorist",
		"Dr. Chiara Rossi, cultural geographer",
		"Dr. Raj Mehta, organizational sociologist",
		"Dr. Linnea Strand, environmental psychologist",
		"Dr. Omar Fahim, political ethnographer",
		"Dr. Freya Berg, computational linguist",
	}

	// Each analyst covers a subset of citizens or all of them
	citizensPerAnalyst := *citizens
	if *analysts > 1 && *citizens > 10 {
		citizensPerAnalyst = (*citizens + *analysts - 1) / *analysts
	}

	for a := 0; a < *analysts; a++ {
		analystName := analystNames[a%len(analystNames)]
		cellName := "analyst"
		if *analysts > 1 {
			cellName = fmt.Sprintf("analyst-%d", a+1)
		}

		start := a * citizensPerAnalyst
		end := start + citizensPerAnalyst
		if end > *citizens {
			end = *citizens
		}
		if start >= *citizens {
			start = 0
			end = *citizens
		}

		assignedCitizens := allCitizens[start:end]

		fmt.Printf("⊢ %s\n", cellName)
		// Givens: all fields from assigned citizens
		for _, c := range assignedCitizens {
			fmt.Printf("  given %s→name\n", c.cellName)
			fmt.Printf("  given %s→morning\n", c.cellName)
			fmt.Printf("  given %s→afternoon\n", c.cellName)
			fmt.Printf("  given %s→evening\n", c.cellName)
			fmt.Printf("  given %s→thoughts\n", c.cellName)
		}

		fmt.Println("  yield social-patterns")
		fmt.Println("  yield emotional-themes")
		fmt.Println("  yield spatial-analysis")
		fmt.Println("  yield notable-interactions")
		fmt.Println("  yield hypothesis")

		// Build the prompt with citizen data sections
		fmt.Printf("  ∴ You are %s studying the population of Millhaven.\n", analystName)
		fmt.Println()
		fmt.Println("    Here are the daily logs of your assigned citizens:")
		fmt.Println()
		for _, c := range assignedCitizens {
			fmt.Printf("    === «%s→name» ===\n", c.cellName)
			fmt.Printf("    Morning: «%s→morning»\n", c.cellName)
			fmt.Printf("    Afternoon: «%s→afternoon»\n", c.cellName)
			fmt.Printf("    Evening: «%s→evening»\n", c.cellName)
			fmt.Printf("    Private thoughts: «%s→thoughts»\n", c.cellName)
			fmt.Println()
		}
		fmt.Println("    Analyze this day's data. Produce:")
		fmt.Println("    1. social-patterns: What social dynamics and relationships do you observe?")
		fmt.Println("    2. emotional-themes: What emotional undercurrents run through the population?")
		fmt.Println("    3. spatial-analysis: How do citizens use and move through the town's spaces?")
		fmt.Println("    4. notable-interactions: Any surprising or noteworthy citizen behaviors?")
		fmt.Println("    5. hypothesis: A testable hypothesis about this community for further study.")
		fmt.Println("  ⊨ social-patterns is a string")
		fmt.Println("  ⊨ emotional-themes is a string")
		fmt.Println("  ⊨ spatial-analysis is a string")
		fmt.Println("  ⊨ notable-interactions is a string")
		fmt.Println("  ⊨ hypothesis is a string")
		fmt.Println()
	}
}

func articlePrefix(occ string) string {
	// "a" or "the" depending on occupation
	if strings.HasPrefix(occ, "the ") || strings.HasPrefix(occ, "owner") || strings.HasPrefix(occ, "head ") {
		return occ
	}
	first := strings.ToLower(occ[:1])
	if first == "a" || first == "e" || first == "i" || first == "o" || first == "u" {
		return "an " + occ
	}
	return "a " + occ
}
